Update hltrainval.py
ImportError: cannot import name 'compare_ssim' from 'skimage.measure' change to from skimage.metrics import structural_similarity
functionality still exists, but under the new skimage.metrics submodule under different names.